---
k3s_version: v1.21.4+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
# extra_server_args: "--cluster-init --tls-san '{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}' --cluster-reset"
# extra_server_args: "--cluster-init --cluster-reset"
extra_server_args: ""
extra_agent_args: ""
