---

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755


- name: Create directory /etc/systemd/system/k3s-node.service.d/
  file:
    path: /etc/systemd/system/k3s-node.service.d/
    state: directory
    mode: 0755

- name: Copy k3s-node override file
  register: k3s_node_service_override
  template:
    src: "override.conf.j2"
    dest: "/etc/systemd/system/k3s-node.service.d/override.conf"
    owner: root
    group: root
    mode: 0644

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
